### ISSUE TITLE
Latest version cannot be obtained via this shortcut

### ISSUE THREAD

**Issue by skinkie** [entur/netex-parser-java#108]
https://github.com/entur/netex-parser-java/blob/master/src/main/java/org/entur/netex/support/NetexVersionHelper.java#L34

This library (and its upstream profile) incorrently state that the version attribute in NeTEx is an integer that increases, so the highest number would be the latest version. This is **not** the case. Starting with: the attribute is not limited to be an integer in the first place.

NeTEx defines a Version object, which similar to ValidBetween states an validity between dates. Version could also be formed as a hierarchy. Given a baseline version, with later updates altering previous contents. This kind of version management in its most extreme case can completely track the state of objects during their lifecycle given a certain period.

The way the Nordic profile 'increment' object versions to state a version per object is not the usage how it was forseen. This behavior makes the fundaments of this library unusable for any other profile that (even partly) implements the version attribute how it was intented.

**Comment by testower** [comment]
Note that OTP makes the same assumptions: https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/main/java/org/opentripplanner/netex/support/NetexVersionHelper.java#LL17C34-L17C34

**Comment by testower** [comment]
Whether or not the Nordic profile is correct in how this is handled is not a discussion I'm going to go attempt to go into. 

I imagine it would be possible to add support for other versioning schemes and make the parser accept a configuration parameter or interface for how to handle it. Anyone is welcome to contribute on that. I don't believe there is anything fundamental about the library that would block that effort.

Or is it not the case that in other profiles, there is such a concept of an entity's "latest" version?

**Comment by skinkie** [comment]
Basically there is no latest version, there is an active version for a specific operating date. Hence a newer version may not contain the data of today.

**Comment by testower** [comment]
Yeah so there is really nothing wrong with implementing an alternative, pluggable handling for this.

**Comment by testower** [comment]
If anyone is interested in working on this issue, feel free to reopen.
